namespace WinIsland.UI;

/// <summary>
/// Lightweight in-app localization (Simplified Chinese default + English).
/// UI strings are resolved through <see cref="Get"/> and view models re-raise
/// PropertyChanged when <see cref="LanguageChanged"/> fires.
/// </summary>
public static class Localization
{
    private static readonly Dictionary<string, string> Zh = new()
    {
        ["AppName"] = "WinIsland",
        ["Settings"] = "设置",
        ["ShowHide"] = "显示 / 隐藏灵动岛",
        ["Island_CenterAlign"] = "居中对齐",
        ["Island_Lock"] = "上锁",
        ["Island_Unlock"] = "解锁",
        ["Island_OnlineLyrics"] = "在线歌词（免配置）",
        ["LyricsWindow"] = "独立歌词窗口",
        ["AutoStart"] = "开机自启",
        ["Exit"] = "退出",
        ["Paused"] = "已暂停",
        ["NoMedia"] = "暂未检测到播放中的媒体",
        ["Source"] = "来源",
        ["LyricsUnavailable"] = "暂无歌词",
        ["Lyrics_Local"] = "本地歌词",
        ["Lyrics_FromCider"] = "Cider 歌词",
        ["Settings_Title"] = "WinIsland 设置",
        ["Settings_General"] = "通用",
        ["Settings_Appearance"] = "外观",
        ["Settings_Media"] = "媒体",
        ["Settings_Lyrics"] = "歌词",
        ["Settings_Cider"] = "Cider",
        ["Settings_About"] = "关于",
        ["General_StartWithWindows"] = "开机自启",
        ["General_StartHidden"] = "启动时隐藏灵动岛",
        ["General_HideWhenNoMedia"] = "无媒体播放时自动隐藏",
        ["General_ShowWhenPaused"] = "暂停时仍然显示",
        ["General_Language"] = "界面语言",
        ["Appearance_Theme"] = "主题",
        ["Appearance_ThemeAuto"] = "跟随系统",
        ["Appearance_ThemeLight"] = "浅色",
        ["Appearance_ThemeDark"] = "深色",
        ["Appearance_Accent"] = "主题色",
        ["Appearance_Position"] = "位置",
        ["Appearance_PositionCenter"] = "顶部居中",
        ["Appearance_PositionRight"] = "顶部右侧",
        ["Appearance_Monitor"] = "显示器",
        ["Appearance_MonitorPrimary"] = "主屏幕",
        ["Appearance_MonitorAll"] = "所有屏幕",
        ["Appearance_MonitorIndex"] = "指定屏幕",
        ["Appearance_MonitorIndexLabel"] = "屏幕编号",
        ["Appearance_OffsetX"] = "水平偏移",
        ["Appearance_OffsetY"] = "垂直偏移",
        ["Appearance_Opacity"] = "不透明度",
        ["Appearance_Compact"] = "紧凑模式显示内容",
        ["Appearance_CompactArt"] = "封面",
        ["Appearance_CompactTitle"] = "歌名",
        ["Appearance_CompactProgress"] = "进度条",
        ["Appearance_CompactShowArt"] = "紧凑模式显示封面",
        ["Appearance_CompactShowTitle"] = "紧凑模式显示歌名",
        ["Appearance_CompactShowProgress"] = "紧凑模式显示进度",
        ["Media_UseSystemVolume"] = "非 Cider 来源时控制系统音量",
        ["Media_SourcePriority"] = "媒体来源优先级：Cider 本地 API → Windows 全局媒体会话 (SMTC) → 窗口标题识别",
        ["Lyrics_Online"] = "在线歌词（网易云，非官方接口，默认关闭）",
        ["Lyrics_Folder"] = "歌词文件夹（留空自动搜索）",
        ["Lyrics_StandaloneWindow"] = "启用独立歌词小窗",
        ["Lyrics_Karaoke"] = "逐字高亮（卡拉OK效果）",
        ["Lyrics_CopyrightNote"] = "在线歌词使用非官方接口，仅供个人学习，请尊重版权。",
        ["Cider_Enabled"] = "启用 Cider 本地 API",
        ["Cider_Port"] = "端口（0 = 自动检测，默认 10767）",
        ["Cider_Token"] = "API Token（可留空）",
        ["Cider_HowTo"] = "在 Cider 中开启：设置 → 连接性 → 允许外部控制（Manage External Application Access），生成 Token 后填入。",
        ["About_Text"] = "WinIsland — Windows 灵动岛\n灵感来自 macOS Dynamic Island。\n基于 .NET 8 + WPF，仅使用系统媒体会话与本地 API。",
        ["Save"] = "保存",
        ["Cancel"] = "取消",
        ["Export"] = "导出配置",
        ["Import"] = "导入配置",
        ["Browse"] = "浏览...",
        ["OpenConfigFolder"] = "打开配置目录",
        ["Diagnostics"] = "诊断信息",
        ["SettingsSaved"] = "设置已保存",
        ["ImportFailed"] = "导入失败：配置文件无效",
        ["ShowIsland"] = "显示灵动岛",
        ["HideIsland"] = "隐藏灵动岛",
        ["RestartHint"] = "部分设置将在重启后完全生效",
        ["Settings_Notifications"] = "通知",
        ["Notifications_Bluetooth"] = "蓝牙设备连接/断开提示",
        ["Notifications_Takeover"] = "接管 Windows 通知（尽力而为）",
        ["Notifications_Timeout"] = "通知显示时长（秒）",
        ["Notifications_Note"] = "Windows 未提供公开的“拦截其它应用通知”API，本功能通过 UI 自动化尽力镜像通知中心，部分通知可能无法捕获。",
        ["Appearance_IslandSize"] = "灵动岛尺寸",
        ["Appearance_CompactWidth"] = "紧凑长度",
        ["Appearance_CompactHeight"] = "紧凑宽度",
        ["Appearance_ExpandedWidth"] = "展开长度",        ["Appearance_Widgets"] = "无媒体时组件",
        ["Appearance_ShowWidgets"] = "无媒体播放时显示组件（时间 / 天气）",
        ["Appearance_WidgetTime"] = "显示时间",
        ["Appearance_WidgetWeather"] = "显示天气",
        ["Appearance_WeatherCity"] = "天气城市（需联网，Open-Meteo）",
        ["Appearance_WidgetNote"] = "天气使用 Open-Meteo 免费接口，仅在你开启并填写城市时联网；城市名可用中文或英文。",        ["Done"] = "完成",
        ["General_AlwaysVisible"] = "灵动岛常驻（始终显示，无媒体时显示时间）",
        ["Settings_Components"] = "组件",
        ["Comp_Header_Name"] = "组件",
        ["Comp_Header_Idle"] = "无歌曲播放时",
        ["Comp_Header_Playing"] = "有歌曲播放时",
        ["Comp_Time"] = "时间",
        ["Comp_Weather"] = "天气",
        ["Comp_Cover"] = "专辑封面",
        ["Comp_Title"] = "歌名",
        ["Comp_Artist"] = "歌手",
        ["Comp_Lyrics"] = "歌词",
        ["Comp_Progress"] = "进度条",
        ["Comp_Note"] = "勾选要在灵动岛上显示的内容；同一组件在「无歌曲播放时」和「有歌曲播放时」可以同时勾选。用▲▼调整时间/天气的摆放顺序。天气组件需要填写城市并联网获取。",        ["Comp_OrderHint"] = "拖动调整摆放顺序",
        ["Comp_Song"] = "歌曲信息",
        ["Media_Apps"] = "媒体程序（可禁用或调整顺序）",
        ["Media_Note"] = "取消勾选=禁用该媒体程序（不再检测）；列表越靠上优先级越高（多个程序同时在播放时优先显示靠上的）。首次运行后会自动列出检测到的媒体程序。",
        ["Settings_MediaInfo"] = "媒体信息展示",
        ["MediaInfo_Show"] = "显示媒体播放信息（歌名/歌手/封面/歌词/进度条）",
        ["MediaInfo_Note"] = "关闭后，灵动岛不显示歌曲相关的播放信息，只按组件设置显示时间/天气等内容；播放控制按钮仍可用。"
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["AppName"] = "WinIsland",
        ["Settings"] = "Settings",
        ["ShowHide"] = "Show / Hide Island",
        ["Island_CenterAlign"] = "Center horizontally",
        ["Island_Lock"] = "Lock",
        ["Island_Unlock"] = "Unlock",
        ["Island_OnlineLyrics"] = "Online lyrics (no setup)",
        ["LyricsWindow"] = "Standalone lyrics window",
        ["AutoStart"] = "Start with Windows",
        ["Exit"] = "Exit",
        ["Paused"] = "Paused",
        ["NoMedia"] = "No media detected",
        ["Source"] = "Source",
        ["LyricsUnavailable"] = "No lyrics available",
        ["Lyrics_Local"] = "Local lyrics",
        ["Lyrics_FromCider"] = "Cider lyrics",
        ["Settings_Title"] = "WinIsland Settings",
        ["Settings_General"] = "General",
        ["Settings_Appearance"] = "Appearance",
        ["Settings_Media"] = "Media",
        ["Settings_Lyrics"] = "Lyrics",
        ["Settings_Cider"] = "Cider",
        ["Settings_About"] = "About",
        ["General_StartWithWindows"] = "Start with Windows",
        ["General_StartHidden"] = "Start with island hidden",
        ["General_HideWhenNoMedia"] = "Hide automatically when no media",
        ["General_ShowWhenPaused"] = "Keep visible while paused",
        ["General_Language"] = "Language",
        ["Appearance_Theme"] = "Theme",
        ["Appearance_ThemeAuto"] = "Follow system",
        ["Appearance_ThemeLight"] = "Light",
        ["Appearance_ThemeDark"] = "Dark",
        ["Appearance_Accent"] = "Accent color",
        ["Appearance_Position"] = "Position",
        ["Appearance_PositionCenter"] = "Top center",
        ["Appearance_PositionRight"] = "Top right",
        ["Appearance_Monitor"] = "Monitor",
        ["Appearance_MonitorPrimary"] = "Primary",
        ["Appearance_MonitorAll"] = "All screens",
        ["Appearance_MonitorIndex"] = "Specific screen",
        ["Appearance_MonitorIndexLabel"] = "Screen #",
        ["Appearance_OffsetX"] = "Horizontal offset",
        ["Appearance_OffsetY"] = "Vertical offset",
        ["Appearance_Opacity"] = "Opacity",
        ["Appearance_Compact"] = "Compact mode content",
        ["Appearance_CompactArt"] = "Artwork",
        ["Appearance_CompactTitle"] = "Title",
        ["Appearance_CompactProgress"] = "Progress",
        ["Appearance_CompactShowArt"] = "Show artwork in compact mode",
        ["Appearance_CompactShowTitle"] = "Show title in compact mode",
        ["Appearance_CompactShowProgress"] = "Show progress in compact mode",
        ["Media_UseSystemVolume"] = "Control system volume for non-Cider sources",
        ["Media_SourcePriority"] = "Source priority: Cider local API → Windows global media session (SMTC) → window title",
        ["Lyrics_Online"] = "Online lyrics (Netease, unofficial, OFF by default)",
        ["Lyrics_Folder"] = "Lyrics folder (leave empty to auto-search)",
        ["Lyrics_StandaloneWindow"] = "Enable standalone lyrics window",
        ["Lyrics_Karaoke"] = "Word-by-word karaoke highlight",
        ["Lyrics_CopyrightNote"] = "Online lyrics use unofficial APIs; personal use only. Respect copyright.",
        ["Cider_Enabled"] = "Enable Cider local API",
        ["Cider_Port"] = "Port (0 = auto-detect, default 10767)",
        ["Cider_Token"] = "API token (optional)",
        ["Cider_HowTo"] = "In Cider: Settings → Connectivity → Manage External Application Access, generate a token and paste it here.",
        ["About_Text"] = "WinIsland — Dynamic Island for Windows\nInspired by macOS Dynamic Island.\nBuilt with .NET 8 + WPF using the system media session and local APIs only.",
        ["Save"] = "Save",
        ["Cancel"] = "Cancel",
        ["Export"] = "Export config",
        ["Import"] = "Import config",
        ["Browse"] = "Browse...",
        ["OpenConfigFolder"] = "Open config folder",
        ["Diagnostics"] = "Diagnostics",
        ["SettingsSaved"] = "Settings saved",
        ["ImportFailed"] = "Import failed: invalid config file",
        ["ShowIsland"] = "Show Island",
        ["HideIsland"] = "Hide Island",
        ["RestartHint"] = "Some settings fully apply after restart",
        ["Settings_Notifications"] = "Notifications",
        ["Notifications_Bluetooth"] = "Bluetooth device connect/disconnect alerts",
        ["Notifications_Takeover"] = "Mirror Windows notifications (best effort)",
        ["Notifications_Timeout"] = "Notification duration (seconds)",
        ["Notifications_Note"] = "Windows has no public API to intercept other apps' toasts; this mirrors the notification center via UI Automation (best effort) and may miss some notifications.",
        ["Appearance_IslandSize"] = "Island size",
        ["Appearance_CompactWidth"] = "Compact length",
        ["Appearance_CompactHeight"] = "Compact width",
        ["Appearance_ExpandedWidth"] = "Expanded length",        ["Appearance_Widgets"] = "Idle widgets",
        ["Appearance_ShowWidgets"] = "Show widgets when no media (time / weather)",
        ["Appearance_WidgetTime"] = "Show time",
        ["Appearance_WidgetWeather"] = "Show weather",
        ["Appearance_WeatherCity"] = "Weather city (requires network, Open-Meteo)",
        ["Appearance_WidgetNote"] = "Weather uses the free Open-Meteo API; it only goes online when enabled with a city.",        ["Done"] = "Done",
        ["General_AlwaysVisible"] = "Island always visible (shows time when idle)",
        ["Settings_Components"] = "Components",
        ["Comp_Header_Name"] = "Component",
        ["Comp_Header_Idle"] = "When no song",
        ["Comp_Header_Playing"] = "When playing",
        ["Comp_Time"] = "Time",
        ["Comp_Weather"] = "Weather",
        ["Comp_Cover"] = "Album art",
        ["Comp_Title"] = "Song title",
        ["Comp_Artist"] = "Artist",
        ["Comp_Lyrics"] = "Lyrics",
        ["Comp_Progress"] = "Progress bar",
        ["Comp_Note"] = "Check what to show on the island; a component can be shown both when idle and when playing. Use up/down to reorder time/weather. Weather needs a city and network.",        ["Comp_OrderHint"] = "Drag to reorder",
        ["Comp_Song"] = "Song info",
        ["Media_Apps"] = "Media apps (disable or reorder)",
        ["Media_Note"] = "Uncheck to disable a media app (not detected); higher in the list = higher priority when several are playing. Detected media apps appear here automatically.",
        ["Settings_MediaInfo"] = "Media info display",
        ["MediaInfo_Show"] = "Show media playback info (title/artist/cover/lyrics/progress)",
        ["MediaInfo_Note"] = "When off, the island hides song-related playback info and only shows configured widgets (time/weather etc.); playback controls remain available."
    };

    private static string _current = "zh-CN";

    public static string CurrentLanguage
    {
        get => _current;
        set
        {
            if (_current == value) return;
            _current = value == "en-US" ? "en-US" : "zh-CN";
            LanguageChanged?.Invoke(null, EventArgs.Empty);
        }
    }

    public static event EventHandler? LanguageChanged;

    public static string Get(string key)
    {
        var table = _current == "en-US" ? En : Zh;
        return table.TryGetValue(key, out var v) ? v : key;
    }
}



