<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>WinIsland</AssemblyName>
    <RootNamespace>WinIsland</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\winisland.ico</ApplicationIcon>
    <Version>1.2.1</Version>
    <AssemblyVersion>1.2.1.0</AssemblyVersion>
    <FileVersion>1.2.1.0</FileVersion>
    <Authors>WinIsland</Authors>
    <Product>WinIsland</Product>
    <Description>macOS-style Dynamic Island for Windows - media controls, lyrics and more.</Description>
    <SatelliteResourceLanguages>en;zh-Hans</SatelliteResourceLanguages>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <NoWarn>;WFAC010</NoWarn>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\winisland.ico" />
  </ItemGroup>

</Project>


